config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  

  delete '/logout',  to: 'sessions#destroy'
  

  get  '/signup',  to: 'users#new'
  
  post '/signup',  to: 'users#create'
  get '/profile', to: 'users#show'

  resources :posts,     only: [:new, :create, :index]
  resources :users, only: [:new, :create, :show]  
  root 'posts#index'

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :remember_token
  before_create :create_session_token
  validates :password, length: { minimum: 6 }

  has_secure_password
  has_many :posts

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def self.digest(string)
    Digest::SHA1.hexdigest string
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def create_session_token
    self.remember_token = User.new_token
    self.remember_digest = User.digest(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  def to_s
    "#{name} as #{username}"
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
    sign_in(user)
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def sign_in(user)
    remember_token = User.new_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    @current_user = user
  end

  def sign_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :logged_in_user, only: %i[create new]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # POST /posts
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to posts_path
      flash[:success] = 'Congratulations, You have Posted on Members Only!!'

    else
      flash.now[:danger] = 'There was a problem with your post'
      render :new
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:content)
  end

  def logged_in_user
    return unless logged_in? == false

    flash[:danger] = 'Please log in.'
    redirect_to login_url
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in user
      remember(user)
      current_user
      redirect_to posts_path
      flash[:success] = 'Thank you for signing in!'
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
    flash[:success] = 'You Have logged Out!!'
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show]
  before_action :not_logged_in_user, only: %i[new create]

  def show
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      remember @user
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def logged_in_user
    return if logged_in?

    flash[:danger] = 'Please log in.'
    redirect_to login_url
  end

  def not_logged_in_user
    return unless logged_in?

    flash[:danger] = 'You are already logged in!'
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = 'Members Only'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user&.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  # Get the username in the view
  def username
    return current_user.username if current_user
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication">Members Only Project</a>
    by <a href="https://github.com/carloshdelreal/members-only">Carlos Del Real & António Fernandes</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", "#" %></li>
      <li><%= link_to "Contact", "#" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all','data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" >
   <div class="container">
    <%= link_to "Members Only", posts_path, id: "logo" %>
    <nav>
       <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Posts", posts_path %></li>
        <% if logged_in? %>
          <% if username %>
            <li><%= link_to "Hello, #{username}", profile_path %></li>
          <% end %>
          <li><%= link_to "Create Post", new_post_path %></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/head'%>
    <%= render 'layouts/shim' %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <%= render 'layouts/header', :username => username %>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>

    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field-text">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <% if logged_in? %>
        <th>User</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <% if logged_in? %>
          <td><%= post.user %></td>
        <% end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form', post: @post %>
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_with model: user, url: '/signup' do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :username %>
  <%= form.text_field :username %>

  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %><br>


    
    <%= form.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>User Profile</h1>
<h3><strong>Name: </strong> <%= @user.name %></h3>
<p><strong>Username: </strong> <%= @user.username %></p>
<p><strong>E-Mail: </strong> <%= @user.email %></p>
<p><strong>Created: </strong> <%= @user.created_at %></p>
<p><strong>Updated: </strong> <%= @user.updated_at %></p>